name: py3.7
channels:
  - menpo
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_0
  - openssl=1.1.1d=h7b6447c_4
  - pip=20.0.2=py37_1
  - python=3.7.6=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=46.0.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - apex==0.1
    - boto3==1.12.18
    - botocore==1.15.18
    - cachetools==4.0.0
    - chardet==3.0.4
    - click==7.1.1
    - docutils==0.15.2
    - filelock==3.0.12
    - future==0.18.2
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.2
    - hydra-core==0.11.3
    - idna==2.9
    - jmespath==0.9.5
    - joblib==0.14.1
    - loguru==0.4.1
    - markdown==3.2.1
    - numpy==1.17.4
    - oauthlib==3.1.0
    - omegaconf==1.4.1
    - pandas==0.25.3
    - pillow==7.0.0
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-dateutil==2.8.1
    - pytorch-lightning==0.6.0
    - pytz==2019.3
    - pyyaml==5.3
    - regex==2020.2.20
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - sacremoses==0.0.38
    - scikit-learn==0.22.2
    - scipy==1.4.1
    - sentencepiece==0.1.85
    - six==1.14.0
    - tensorboard==2.1.1
    - tokenizers==0.5.0
    - torch==1.4.0
    - torchvision==0.4.2
    - tqdm==4.40.0
    - transformers==2.5.0
    - urllib3==1.25.8
    - werkzeug==1.0.0

